name: Simple release tool
description: some text here
author: slowpeek

inputs:
  files:
    description: >
      Multiline list of files to include in release. Per file special
      treatment can be toggled with flags. Separate flags with tilde
      like 'README.org ~doc ~toc'.
    required: true
    default: ''

  bump-version:
    description: >
      If not empty, a commit will be pushed to the repository with 'v'
      flagged files having their versions set to the current tag
      postfixed with this option's value.
    required: true
    default: ''

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/release.sh
      shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
        INPUT_BUMP_VERSION: ${{ inputs.bump-version }}
        GITHUB_TOKEN: ${{ github.token }}
