name: Simple release tool
description: some text here
author: slowpeek

inputs:
  files:
    description: >
      Multiline list of files to include in release. Per file special
      treatment can be toggled with flags. Separate flags with plus
      sign like 'README.org +doc +toc'.
    required: true
    default: ''

  bump-version:
    description: >
      If enabled, a commit will be pushed to the repository with files
      possessing 'v' flag having their version set to the current tag
      with '+dev' suffix.
    required: true
    default: no

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/release.sh
      shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
        INPUT_BUMP_VERSION: ${{ inputs.bump-version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
